version: "3"

services:
  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  pact_broker:
    image: pactfoundation/pact-broker
    # build: .
    ports:
      - "9292:9292"
    depends_on:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
      PACT_BROKER_WEBHOOK_HOST_WHITELIST: ["github.com","travis.org"]
      PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: ["http", "https"]
      PACT_BROKER_PORT: "9292"
      PACT_BROKER_BASE_URL: "https://yyan.io"
      PACT_BROKER_BASIC_AUTH_USERNAME: CSPUsr2
      PACT_BROKER_BASIC_AUTH_PASSWORD: Password1


#  can-i-deploy:
#    image: pactfoundation/pact-cli
#    depends_on:
#      - pact_broker
#    environment:
#      PACT_BROKER_BASE_URL: https://yyan.io
#      SSL_CERT_FILE: /tmp/cacert.crt
#    volumes:
#      - ${PWD}/ssl/nginx-selfsigned.crt:/tmp/cacert.crt
#    command: broker can-i-deploy --pacticipant "Example App" --latest

volumes:
  postgres-volume: